#!/bin/bash 
# Script 5: Open Source Manifesto Generator 
# Author: Pranati Vashishtha | Course: Open Source Software 
echo "Answer three questions to generate your manifesto." 
echo "" 
read -p "1. Name one open-source tool you use every day: " TOOL 
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM 
read -p "3. Name one thing you would build and share freely: " BUILD 
DATE=$(date '+%d %B %Y') 
OUTPUT="manifesto_$(whoami).txt" 
# --- TODO Completed --- 
# Compose a paragraph using $TOOL, $FREEDOM, $BUILD 
# and write it to $OUTPUT using echo and >> 
# Alias concept demonstrated via comment: 
# alias manifesto='bash ~/script5_manifesto.sh' # shortcut to run this script quickly 
MANIFESTO=" 
============================================ 
MY OPEN SOURCE MANIFESTO 
============================================ 
Generated by : $(whoami) 
Date : $DATE 
-------------------------------------------- 
I believe in the power of open source. 
Every day, I rely on $TOOL — a tool built 
by the community, for the community. 
To me, freedom means $FREEDOM. 
It is this spirit that drives the open source 
movement forward, one commit at a time. 
If I could build anything and share it freely, 
it would be $BUILD — because knowledge grows 
when it is given away, not hoarded. 
Open source is not just software. 
It is a philosophy. It is a way of life. 
\"Given enough eyeballs, all bugs are shallow.\" 
— Linus's Law 
============================================ 
" 
# Write manifesto to file using > 
echo "$MANIFESTO" > "$OUTPUT" 
echo "Manifesto saved to $OUTPUT" 
cat $OUTPUT 
